import {useEffect,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useSearchParams} from "react-router-dom";
import {api,ApiError,DataMode,EnvironmentFilter} from "../services/api";
import {EmptyState,ErrorState,MetricCard,PageHeader,Section,StatusBadge,formatLocalTime,formatValue} from "../components/console/ConsoleUI";
import {BusinessSkillAction} from "../components/console/BusinessSkillAction";
import {Bar,BarChart,CartesianGrid,Cell,ComposedChart,Legend,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";

const message=(error:unknown)=>error instanceof ApiError?error.message:error instanceof Error?error.message:"请求失败";
const tone=(state:unknown):"success"|"warning"|"danger"|"neutral"|"info"=>{
  const value=String(state??"").toUpperCase();
  if(["READY","CLOSED","SUCCESS","ACTIVE","VALIDATED","APPROVED"].includes(value))return "success";
  if(["OPEN","FAILED","BLOCKED","ROLLED_BACK","DISABLED"].includes(value))return "danger";
  if(["HALF_OPEN","PROPOSED","STALE","DEGRADED","UNAVAILABLE"].includes(value))return "warning";
  return "neutral";
};

const errorNames:Record<string,string>={historical_platform_error:"历史平台错误",network_timeout:"网络超时",
  protocol_conversion_error:"协议转换错误",sse_protocol_error:"SSE 协议错误",timeout:"请求超时",
  upstream_5xx:"上游服务错误",user_authentication_error:"用户鉴权错误",user_parameter_error:"用户参数错误",
  rate_limited:"请求限流",unknown:"未分类错误"};
const shortId=(value:string|null)=>value?`${value.slice(0,8)}…${value.slice(-4)}`:"—";
const percent=(value:number|null|undefined)=>value==null?"无数据":`${(value*100).toFixed(1)}%`;
const millis=(value:number|null|undefined)=>value==null?"无数据":`${Math.round(value).toLocaleString("zh-CN")} ms`;
const delta=(value:number|null|undefined)=>value==null?"无上周期数据":`${value>=0?"+":""}${(value*100).toFixed(1)}%`;
const money=(value:string|null|undefined)=>value==null?"无数据":`¥${Number(value).toFixed(6)}`;
const timeTick=(value:string)=>formatLocalTime(value).slice(5,16);

export function MonitoringOverviewPage({environment}:{mode:DataMode;environment:EnvironmentFilter}){
  const [params,setParams]=useSearchParams();
  const callEnvironment=environment==="all"?"china_uat":environment;
  const range=params.get("time_range")??"24h";const traffic=params.get("traffic_class")??"business";
  const model=params.get("model_id")??"";const stream=params.get("stream")??"all";
  const source=params.get("source_type")??"all";const [autoRefresh,setAutoRefresh]=useState(true);
  const [start,setStart]=useState(params.get("start")??"");const [end,setEnd]=useState(params.get("end")??"");
  const update=(key:string,value:string)=>{
    const next=new URLSearchParams(params);
    if(value){next.set(key,value)}else{next.delete(key)}
    setParams(next,{replace:true});
  };
  const filters={environment_id:callEnvironment,time_range:range,traffic_class:traffic,source_type:source,
    ...(model?{model_id:model}:{}),...(stream!=="all"?{stream:stream==="stream"}:{}),
    ...(range==="custom"&&start&&end?{start:new Date(start).toISOString(),end:new Date(end).toISOString()}: {})};
  const ready=range!=="custom"||Boolean(start&&end);
  const query=useQuery({queryKey:["observability-overview",filters],queryFn:({signal})=>api.observabilityOverview(filters,signal),enabled:ready,refetchInterval:autoRefresh?5000:false,placeholderData:previous=>previous});
  const data=query.data;const k=data?.kpis;const records=data?.recent_records??[];
  const chartEmpty=!data?.coverage.records;
  return <main className="monitoring-overview-page"><PageHeader title="监控总览" description="用统一调用日志观察请求、延迟、Token、费用与可靠性；业务流量默认不受探测记录污染。"/>
    <section className="monitor-filter-rail" aria-label="监控筛选"><label>环境<select value={callEnvironment} disabled><option value="china_uat">国内 UAT</option></select></label><label>时间<select value={range} onChange={e=>update("time_range",e.target.value)}><option value="5m">最近 5 分钟</option><option value="1h">最近 1 小时</option><option value="24h">最近 24 小时</option><option value="7d">最近 7 天</option><option value="custom">自定义</option></select></label><label>流量<select value={traffic} onChange={e=>update("traffic_class",e.target.value)}><option value="business">业务流量</option><option value="probe">探测流量</option><option value="all">全部流量</option></select></label><label>模型<select value={model} onChange={e=>update("model_id",e.target.value)}><option value="">全部模型</option>{data?.filters.models.map(item=><option key={item}>{item}</option>)}</select></label><label>响应<select value={stream} onChange={e=>update("stream",e.target.value)}><option value="all">全部</option><option value="stream">流式</option><option value="nonstream">非流式</option></select></label><label>来源<select value={source} onChange={e=>update("source_type",e.target.value)}><option value="all">全部来源</option><option value="historical">历史日志</option><option value="realtime">实时执行</option></select></label>{range==="custom"&&<><label>开始<input type="datetime-local" value={start} onChange={e=>{setStart(e.target.value);update("start",e.target.value)}}/></label><label>结束<input type="datetime-local" value={end} onChange={e=>{setEnd(e.target.value);update("end",e.target.value)}}/></label></>}<label className="monitor-switch"><input type="checkbox" checked={autoRefresh} onChange={e=>setAutoRefresh(e.target.checked)}/>自动刷新</label><button onClick={()=>query.refetch()} disabled={query.isFetching||!ready}>{query.isFetching?"刷新中…":"刷新"}</button><time>更新 {formatLocalTime(data?.generated_at)}</time></section>
    {!ready?<EmptyState title="请选择完整时间范围" description="填写开始和结束时间后再读取监控数据。"/>:query.error?<ErrorState title="监控数据读取失败" description={message(query.error)} onRetry={()=>query.refetch()}/>:query.isLoading?<p role="status">正在聚合真实监控数据…</p>:chartEmpty?<EmptyState title="当前筛选范围没有真实调用记录" description="调整时间或数据来源；页面不会生成 Demo 指标。"/>:<>
      <section className="monitor-kpi-grid" aria-label="核心指标"><article><span>请求数</span><strong>{k?.requests.toLocaleString("zh-CN")}</strong><small>{delta(k?.deltas.requests)} · 覆盖 {k?.requests}/{k?.requests}</small></article><article><span>成功率</span><strong>{percent(k?.success_rate)}</strong><small>{delta(k?.deltas.success_rate)} · n={k?.requests}</small></article><article><span>P95 延迟</span><strong>{millis(k?.p95_ms)}</strong><small>{delta(k?.deltas.p95_ms)} · 覆盖 {k?.latency_coverage}/{k?.requests}</small></article><article><span>首 Token P95</span><strong>{millis(k?.ttft_p95_ms)}</strong><small>{delta(k?.deltas.ttft_p95_ms)} · 覆盖 {k?.ttft_coverage}/{k?.requests}</small></article><article><span>总 Token</span><strong>{k?.tokens.toLocaleString("zh-CN")}</strong><small>{delta(k?.deltas.tokens)} · 覆盖 {k?.token_coverage}/{k?.requests}</small></article><article className="cost-kpi"><span>可观测实际费用</span><strong>{money(k?.actual_cost)}</strong><small>覆盖 {k?.cost_coverage}/{k?.requests} · {k?.pending_cost_count} 条待同步</small></article></section>
      <section className="cost-ledger-strip"><div><span>Provider 实际费用</span><b>{money(k?.provider_actual_cost)}</b></div><div><span>历史实际费用</span><b>{money(k?.historical_actual_cost)}</b></div><div><span>版本化估算费用</span><b>{money(k?.estimated_cost)}</b></div><div><span>待 Provider 同步</span><b>{k?.pending_cost_count??0} 条</b></div></section>
      <div className="monitor-chart-grid"><Section title="请求量与成功率" description="柱形区分业务与探测请求；成功率使用右侧坐标轴。"><div className="monitor-chart" role="img" aria-label="请求量与成功率时间序列图"><ResponsiveContainer width="100%" height={320}><ComposedChart data={data?.request_series}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time" tickFormatter={timeTick}/><YAxis yAxisId="count" allowDecimals={false}/><YAxis yAxisId="rate" orientation="right" domain={[0,1]} tickFormatter={v=>`${Math.round(v*100)}%`}/><Tooltip labelFormatter={v=>formatLocalTime(String(v))}/><Legend/><Bar yAxisId="count" dataKey="business" name="业务请求" stackId="requests" fill="#506642"/><Bar yAxisId="count" dataKey="probe" name="探测请求" stackId="requests" fill="#a9b78b"/><Line yAxisId="rate" dataKey="success_rate" name="成功率" stroke="#c47a32" strokeWidth={2} dot={false}/></ComposedChart></ResponsiveContainer></div><details><summary>查看数据表</summary><table><tbody>{data?.request_series.map(row=><tr key={row.time}><td>{formatLocalTime(row.time)}</td><td>{row.requests} 次</td><td>{percent(row.success_rate)}</td></tr>)}</tbody></table></details></Section>
      <Section title="延迟趋势" description="总耗时 P50/P95/P99 与流式首 Token P95 分开计量。"><div className="monitor-chart" role="img" aria-label="延迟与首Token趋势图"><ResponsiveContainer width="100%" height={320}><LineChart data={data?.latency_series}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time" tickFormatter={timeTick}/><YAxis unit="ms"/><Tooltip labelFormatter={v=>formatLocalTime(String(v))}/><Legend/><Line dataKey="p50_ms" name="P50" stroke="#72855b" dot={false}/><Line dataKey="p95_ms" name="P95" stroke="#c47a32" dot={false}/><Line dataKey="p99_ms" name="P99" stroke="#a6493f" dot={false}/><Line dataKey="ttft_p95_ms" name="首 Token P95" stroke="#537985" strokeDasharray="5 4" dot={false}/></LineChart></ResponsiveContainer></div></Section>
      <Section title="Token 趋势" description="缓存输入 Token 是输入 Token 的组成部分，单独展示但不重复计入总量。"><div className="monitor-chart" role="img" aria-label="Token组成趋势图"><ResponsiveContainer width="100%" height={300}><BarChart data={data?.token_series}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time" tickFormatter={timeTick}/><YAxis/><Tooltip labelFormatter={v=>formatLocalTime(String(v))}/><Legend/><Bar dataKey="input_tokens" name="输入 Token" stackId="tokens" fill="#506642"/><Bar dataKey="cached_tokens" name="缓存输入 Token" stackId="tokens" fill="#93a278"/><Bar dataKey="output_tokens" name="输出 Token" stackId="tokens" fill="#c47a32"/></BarChart></ResponsiveContainer></div></Section>
      <Section title="费用趋势" description="实际费用与版本化估算分开；待同步记录不绘制为 0。"><div className="monitor-chart" role="img" aria-label="费用口径趋势图"><ResponsiveContainer width="100%" height={300}><LineChart data={data?.cost_series}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time" tickFormatter={timeTick}/><YAxis/><Tooltip labelFormatter={v=>formatLocalTime(String(v))}/><Legend/><Line dataKey="provider_actual" name="Provider 实际" stroke="#395f4b" connectNulls={false}/><Line dataKey="historical_actual" name="历史实际" stroke="#72855b" connectNulls={false}/><Line dataKey="estimated" name="版本化估算" stroke="#c47a32" strokeDasharray="5 4" connectNulls={false}/></LineChart></ResponsiveContainer></div></Section></div>
      <div className="monitor-chart-grid"><Section title="模型调用排行" description="前 10 个真实模型；点击后将该模型带入统一筛选。"><div className="monitor-chart" role="img" aria-label="模型调用次数水平条形图"><ResponsiveContainer width="100%" height={Math.max(280,(data?.model_distribution.length??0)*38)}><BarChart data={data?.model_distribution} layout="vertical" margin={{left:24}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" allowDecimals={false}/><YAxis dataKey="model_id" type="category" width={145} tickFormatter={v=>String(v).length>20?`${String(v).slice(0,18)}…`:String(v)}/><Tooltip/><Bar dataKey="request_count" name="调用次数" fill="#506642" onClick={row=>update("model_id",String(row.model_id))}/></BarChart></ResponsiveContainer></div></Section>
      <Section title="调用形态" description="Completion流式、非流式与非Completion请求分开统计。"><div className="monitor-chart donut" role="img" aria-label="流式与非流式调用环形图"><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={[{name:"流式",value:data?.stream_distribution.stream??0},{name:"非流式",value:data?.stream_distribution.nonstream_completion??0},{name:"非 Completion",value:data?.stream_distribution.non_completion??0}]} dataKey="value" nameKey="name" innerRadius={68} outerRadius={98} label>{["#506642","#93a278","#c47a32"].map(color=><Cell key={color} fill={color}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer><strong>{k?.requests}<small>总请求</small></strong></div></Section>
      <Section title="错误分类" description="主视图使用中文分类；技术代码保留在提示和技术详情中。">{data?.error_distribution.length?<div className="error-bars">{data.error_distribution.map(row=><a key={row.code} href={`/observability/errors?error_category=${encodeURIComponent(row.code)}`} title={row.code}><span>{errorNames[row.code]??"其他错误"}</span><i style={{width:`${Math.max(4,row.count/Math.max(...data.error_distribution.map(x=>x.count))*100)}%`}}/><b>{row.count}</b></a>)}</div>:<EmptyState title="当前范围没有错误" description="所选真实日志中没有失败分类。"/>}</Section>
      <Section title="可靠性" description="重试、Fallback 与熔断状态保持独立口径。"><div className="reliability-grid"><div><span>Fallback 率</span><b>{percent(data?.reliability.fallback_rate)}</b></div><div><span>重试率</span><b>{percent(data?.reliability.retry_rate)}</b></div><div><span>已熔断</span><b>{data?.reliability.open_count}</b></div><div><span>半开探测</span><b>{data?.reliability.half_open_count}</b></div><div><span>活动探针</span><b>{data?.reliability.active_probes}</b></div></div>{!data?.reliability.timeline.length?<p className="compact-empty">当前筛选范围内暂无 Fallback 或熔断转换记录。</p>:<ol className="reliability-timeline">{data.reliability.timeline.map((item,index)=><li key={index}>{String(item.state??"状态变化")}</li>)}</ol>}</Section></div>
      <section className={`freshness-rail ${data?.freshness.provider_log_status==="ready"?"fresh":"partial"}`}><b>数据状态</b><span>水位 {data?.freshness.watermark??"无"}</span><span>最后同步 {formatLocalTime(data?.freshness.last_synced_at)}</span><span>历史 {data?.freshness.source_counts.historical_uat_csv??0}</span><span>实时 {data?.freshness.source_counts.realtime_execution??0}</span><span>实际费用覆盖 {data?.coverage.actual_cost}/{data?.coverage.records}</span><span>{data?.freshness.provider_log_status==="ready"?"Provider 日志已同步":"Provider 日志部分覆盖"}</span></section>
      <Section title="最近请求" description="ID 使用缩略显示，可复制完整值并继续进入执行或决策详情。"><div className="table-scroll"><table className="console-table monitor-records"><thead><tr><th>时间</th><th>流量</th><th>模型</th><th>状态</th><th>总耗时</th><th>首 Token</th><th>Token</th><th>费用</th><th>Request ID</th><th>decision_id</th><th>操作</th></tr></thead><tbody>{records.map((row,index)=><tr key={`${row.request_id}-${index}`}><td>{formatLocalTime(row.occurred_at)}</td><td>{row.traffic_class==="probe"?"探测":"业务"}</td><td>{row.model_id}</td><td><StatusBadge tone={row.status==="SUCCESS"?"success":"danger"}>{row.status==="SUCCESS"?"成功":"失败"}</StatusBadge></td><td>{millis(row.total_latency_ms)}</td><td>{millis(row.first_token_ms)}</td><td>{row.tokens.toLocaleString("zh-CN")}</td><td title={row.cost_type??""}>{row.cost==null?"待同步":money(row.cost)}</td><td><button className="copy-id" title={row.request_id??""} onClick={()=>row.request_id&&navigator.clipboard.writeText(row.request_id)}>{shortId(row.request_id)}</button></td><td><button className="copy-id" title={row.decision_id??""} onClick={()=>row.decision_id&&navigator.clipboard.writeText(row.decision_id)}>{shortId(row.decision_id)}</button></td><td>{row.request_id&&<a href={`/routing/runs?request_id=${encodeURIComponent(row.request_id)}`}>执行详情</a>} {row.decision_id&&<a href={`/routing/decisions/${encodeURIComponent(row.decision_id)}`}>查看决策</a>} {row.error_category&&<a href={`/observability/errors?error_category=${encodeURIComponent(row.error_category)}`}>查看错误</a>}</td></tr>)}</tbody></table></div><details className="performance-technical"><summary>技术详情</summary><pre>{JSON.stringify({scope:data?.scope,coverage:data?.coverage,source_types:data?.freshness.source_counts},null,2)}</pre></details></Section>
    </>}</main>;
}

export function SchedulerPerformancePage(){
  const [range,setRange]=useState("24h");const [trafficClass,setTrafficClass]=useState("business");
  const [start,setStart]=useState("");const [end,setEnd]=useState("");
  const filters={environment_id:"china_uat",time_range:range,traffic_class:trafficClass,
    ...(range==="custom"&&start&&end?{start:new Date(start).toISOString(),end:new Date(end).toISOString()}: {})};
  const customReady=range!=="custom"||Boolean(start&&end);
  const query=useQuery({queryKey:["scheduler-performance",filters],queryFn:({signal})=>api.schedulerPerformance(filters,signal),refetchInterval:5000,enabled:customReady});
  const data=query.data;const k=data?.kpis;const stageSeries=data?.stage_series??[];const latencySeries=data?.latency_series??[];
  const stageDistribution=data?.stage_distribution??[];const providerComparison=data?.provider_comparison??[];
  const strategyComparison=data?.strategy_comparison??[];const recentRecords=data?.recent_records??[];
  const coverage=data?.coverage;const freshness=data?.freshness;const ms=(value:number|null|undefined)=>value==null?"未提供":`${value.toFixed(2)} ms`;
  const stageNames:Record<string,string>={request_validation:"请求校验",candidate_discovery:"候选发现",capability_filter:"能力过滤",
    metrics_read:"指标读取",constraint_filter:"约束过滤",scoring:"评分",deterministic_sort:"排序",fallback_plan:"备用顺序",
    decision_persistence:"持久化",audit_write:"审计"};
  const latest=()=>{if(!data?.freshness.latest_record_at)return;const point=new Date(data.freshness.latest_record_at);
    setStart(new Date(point.getTime()-60*60*1000).toISOString().slice(0,16));setEnd(new Date(point.getTime()+60*60*1000).toISOString().slice(0,16));setRange("custom")};
  return <div className="scheduler-performance-page"><PageHeader title="调度性能" description="观察调度器自身的计算与本地持久化开销；模型响应、网络与流式生成单独计量。"/>
    <Section title="观测范围" description="默认最近 24 小时；探测流量与业务流量分开统计。"><div className="performance-filters"><label>时间范围<select aria-label="统计范围" value={range} onChange={event=>setRange(event.target.value)}><option value="5m">最近 5 分钟</option><option value="1h">最近 1 小时</option><option value="24h">最近 24 小时</option><option value="7d">最近 7 天</option><option value="custom">自定义</option></select></label><label>流量类型<select value={trafficClass} onChange={event=>setTrafficClass(event.target.value)}><option value="business">业务流量</option><option value="probe">探测流量</option></select></label>{range==="custom"&&<><label>开始<input type="datetime-local" value={start} onChange={event=>setStart(event.target.value)}/></label><label>结束<input type="datetime-local" value={end} onChange={event=>setEnd(event.target.value)}/></label></>}</div></Section>
    {query.error?<ErrorState title="调度性能读取失败" description={message(query.error)} onRetry={()=>query.refetch()}/>:query.isLoading?<p role="status">正在读取调度性能…</p>:!k?.request_count?<Section title="当前范围没有记录"><EmptyState title="当前时间范围暂无调度性能记录" description={data?.freshness.latest_record_at?`最近一条记录时间为 ${formatLocalTime(data.freshness.latest_record_at)}。`:"尚未产生接入真实调度链路的性能 Span。"}/>{data?.freshness.latest_record_at&&<button onClick={latest}>一键查看最近数据</button>}</Section>:<>
      <div className="performance-kpis"><MetricCard label="调度请求" value={k.request_count}/><MetricCard label="Scheduler P50" value={ms(k.scheduler_p50_ms)}/><MetricCard label="Scheduler P95" value={ms(k.scheduler_p95_ms)}/><MetricCard label="Scheduler P99" value={ms(k.scheduler_p99_ms)}/><MetricCard label="端到端占比" value={k.scheduler_end_to_end_ratio==null?"未提供":`${(k.scheduler_end_to_end_ratio*100).toFixed(2)}%`}/><MetricCard label="最大开销阶段" value={stageNames[k.largest_stage??""]??k.largest_stage??"未提供"}/></div>
      <div className="performance-chart-grid"><Section title="阶段耗时趋势" description="每根柱表示一次真实请求，阶段堆叠不含 Provider。"><div className="performance-chart"><ResponsiveContainer width="100%" height={300}><BarChart data={stageSeries}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time" tickFormatter={value=>formatLocalTime(value).slice(11,16)}/><YAxis unit="ms"/><Tooltip/><Legend/>{["candidate_discovery","capability_filter","metrics_read","constraint_filter","scoring","deterministic_sort","decision_persistence","audit_write"].map((stage,index)=><Bar key={stage} dataKey={stage} name={stageNames[stage]} stackId="stages" fill={["#526b3f","#71884f","#94a66e","#b4bc8a","#395e57","#587b71","#94734e","#b09168"][index]}/>)}</BarChart></ResponsiveContainer></div></Section>
      <Section title="Scheduler 总耗时趋势" description="滚动分位数来自当前所选真实样本。"><div className="performance-chart"><ResponsiveContainer width="100%" height={300}><LineChart data={latencySeries}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time" tickFormatter={value=>formatLocalTime(value).slice(11,16)}/><YAxis unit="ms"/><Tooltip/><Legend/><Line dataKey="p50_ms" name="P50" stroke="#526b3f" dot={false}/><Line dataKey="p95_ms" name="P95" stroke="#a56b33" dot={false}/><Line dataKey="p99_ms" name="P99" stroke="#9a443a" dot={false}/></LineChart></ResponsiveContainer></div></Section></div>
      <div className="performance-chart-grid"><Section title="耗时构成" description="平均耗时、P95、占比与样本量均由后端聚合。"><div className="stage-bars">{stageDistribution.filter(row=>row.sample_count).map(row=><div key={row.stage}><header><b>{stageNames[row.stage]??row.stage}</b><span>平均 {ms(row.average_ms)} · P95 {ms(row.p95_ms)} · n={row.sample_count}</span></header><i style={{width:`${Math.max(2,(row.share??0)*100)}%`}}/></div>)}</div></Section>
      <Section title="Scheduler 与 Provider" description="Provider 网络与模型响应时间不属于 Scheduler 开销。"><div className="performance-chart"><ResponsiveContainer width="100%" height={300}><BarChart data={providerComparison}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time" tickFormatter={value=>formatLocalTime(value).slice(11,16)}/><YAxis unit="ms"/><Tooltip/><Legend/><Bar dataKey="scheduler_ms" name="Scheduler" fill="#526b3f"/><Bar dataKey="provider_ms" name="Provider" fill="#c08a50"/><Bar dataKey="end_to_end_ms" name="端到端" fill="#6f8195"/></BarChart></ResponsiveContainer></div></Section></div>
      <Section title="策略对比" description="比较基线、延迟优先与成本优先的调度开销；没有样本时不补零。"><div className="table-scroll"><table className="console-table"><thead><tr><th>策略</th><th>样本</th><th>P50</th><th>P95</th><th>平均候选</th><th>平均过滤</th><th>平均评分</th></tr></thead><tbody>{strategyComparison.map(row=><tr key={row.strategy_id}><td>{row.strategy_id}</td><td>{row.sample_count}</td><td>{ms(row.p50_ms)}</td><td>{ms(row.p95_ms)}</td><td>{row.average_candidate_count?.toFixed(1)??"未提供"}</td><td>{row.average_filtered_count?.toFixed(1)??"未提供"}</td><td>{ms(row.average_scoring_ms)}</td></tr>)}</tbody></table></div></Section>
      <Section title="逐请求性能" description={`数据更新时间 ${formatLocalTime(freshness?.generated_at)}；Provider 覆盖 ${coverage?.provider_samples??0}/${coverage?.scheduler_samples??0}。`}><div className="table-scroll"><table className="console-table"><thead><tr><th>时间</th><th>Request ID</th><th>decision_id</th><th>策略 / 模型</th><th>候选 / 过滤</th><th>Scheduler</th><th>Provider</th><th>端到端</th><th>状态</th><th>操作</th></tr></thead><tbody>{recentRecords.map(row=><tr key={row.local_request_id}><td>{formatLocalTime(row.occurred_at)}</td><td><code>{row.local_request_id}</code></td><td><code>{row.decision_id??"未生成"}</code></td><td>{row.strategy_id}<small>{row.model_id??"未记录"}</small></td><td>{row.candidate_count??"—"} / {row.filtered_count??"—"}</td><td>{ms(row.scheduler_total_ms)}</td><td>{ms(row.provider_latency_ms)}</td><td>{ms(row.end_to_end_ms)}</td><td><StatusBadge tone={row.success?"success":"danger"}>{row.success?"成功":"失败"}</StatusBadge></td><td>{row.decision_id?<a href={`/routing/decisions/${encodeURIComponent(row.decision_id)}`}>决策详情</a>:"Span 详情"}</td></tr>)}</tbody></table></div><details className="performance-technical"><summary>技术详情</summary><pre>{JSON.stringify({scope:data?.scope,coverage},null,2)}</pre></details></Section>
    </>}</div>;
}

export function CircuitBreakerPage(){
  const qc=useQueryClient();
  const query=useQuery({queryKey:["circuit-breaker-page"],queryFn:({signal})=>api.circuitBreakerStatus(signal)});
  const [circuitId,setCircuitId]=useState("");
  const [selected,setSelected]=useState("");
  const detail=useQuery({queryKey:["circuit-transitions",selected],queryFn:({signal})=>api.circuitBreakerTransitions(selected,signal),enabled:Boolean(selected)});
  const event=useMutation({mutationFn:(action:'success'|'failure')=>api.recordCircuitEvent(circuitId.trim(),action),onSuccess:async()=>{setSelected(circuitId.trim());await qc.invalidateQueries({queryKey:["circuit-breaker-page"]});await qc.invalidateQueries({queryKey:["circuit-transitions",circuitId.trim()]})}});
  return <><PageHeader title="熔断与恢复" description="状态机和审计由本地持久化服务驱动；测试事件不调用任何外部模型。"/>
    <BusinessSkillAction skillId="operate-circuit-breaker" label="通过 Skill 打开熔断器" argumentsValue={{action:"open",circuit_id:circuitId.trim(),reason:"操作员在熔断页面发起受控操作"}} disabledReason={circuitId.trim()?undefined:"请先填写熔断器 ID"} confirmation/>
    <div className="metric-grid four"><MetricCard label="健康" value={query.data?.state_counts.CLOSED??0}/><MetricCard label="熔断" value={query.data?.state_counts.OPEN??0}/><MetricCard label="半开" value={query.data?.state_counts.HALF_OPEN??0}/><MetricCard label="活动探针" value={query.data?.active_probe_leases??0}/></div>
    <Section title="受控本地事件" description="用于验证 CLOSED → OPEN → HALF_OPEN → CLOSED/OPEN；不会生成外部请求。"><div className="inline-fields"><label>熔断器 ID<input value={circuitId} onChange={event=>setCircuitId(event.target.value)} placeholder="例如 channel-a:model-x"/></label><div className="section-footer"><button disabled={!circuitId.trim()||event.isPending} onClick={()=>event.mutate('failure')}>记录失败</button><button className="secondary" disabled={!circuitId.trim()||event.isPending} onClick={()=>event.mutate('success')}>记录成功</button></div></div>{event.error&&<ErrorState title="事件被拒绝" description={message(event.error)}/>}</Section>
    <Section title="当前熔断器">{query.error?<ErrorState title="熔断状态读取失败" description={message(query.error)} onRetry={()=>query.refetch()}/>:query.data?.items.length?<div className="table-scroll"><table className="console-table"><thead><tr><th>ID</th><th>状态</th><th>打开时间</th><th>冷却至</th><th>修订</th><th>操作</th></tr></thead><tbody>{query.data.items.map(row=><tr key={row.circuit_id}><td>{row.circuit_id}</td><td><StatusBadge tone={tone(row.state)}>{row.state}</StatusBadge></td><td>{formatLocalTime(row.opened_at)}</td><td>{formatLocalTime(row.cooldown_until)}</td><td>{row.revision}</td><td><button className="text-button" onClick={()=>{setCircuitId(row.circuit_id);setSelected(row.circuit_id)}}>查看事件</button></td></tr>)}</tbody></table></div>:<EmptyState title="尚无熔断状态" description="输入一个熔断器 ID 并记录本地成功或失败事件即可创建可审计状态。"/>}</Section>
    {selected&&<Section title="转换审计" description={selected}>{detail.error?<ErrorState title="转换记录读取失败" description={message(detail.error)}/>:detail.data?.items.length?<div className="table-scroll"><table className="console-table"><tbody>{detail.data.items.map((row,index)=><tr key={String(row.audit_id??index)}><td>{formatLocalTime(row.created_at)}</td><td>{formatValue(row.from_state)} → {formatValue(row.to_state)}</td><td>{formatValue(row.reason)}</td></tr>)}</tbody></table></div>:<EmptyState title="尚无状态转换" description="低于失败阈值的事件不会产生状态转换。"/>}</Section>}
  </>;
}

export function ProbeTasksPage(){
  const qc=useQueryClient();
  const tasks=useQuery({queryKey:["probe-tasks"],queryFn:({signal})=>api.probeTasks(signal)});
  const governance=useQuery({queryKey:["probe-governance-page"],queryFn:({signal})=>api.probeGovernanceStatus(signal)});
  const [name,setName]=useState("");const [channel,setChannel]=useState("");const [model,setModel]=useState("");
  const [template,setTemplate]=useState<'mock_success'|'mock_failure'>("mock_success");
  const [frequency,setFrequency]=useState("");const [count,setCount]=useState("");const [concurrency,setConcurrency]=useState("");
  const [deadline,setDeadline]=useState("");const [stopCondition,setStopCondition]=useState<'request_limit'|'first_failure'>("request_limit");
  const refresh=()=>qc.invalidateQueries({queryKey:["probe-tasks"]});
  const create=useMutation({mutationFn:()=>api.createProbeTask({name,environment_id:"china_uat",channel_id:channel,
    model_id:model,request_template:template,frequency_seconds:Number(frequency),max_requests:Number(count),
    max_concurrency:Number(concurrency),deadline:new Date(deadline).toISOString(),stop_condition:stopCondition}),onSuccess:refresh});
  const start=useMutation({mutationFn:(id:string)=>api.startProbeTask(id),onSuccess:refresh});
  const stop=useMutation({mutationFn:(id:string)=>api.stopProbeTask(id),onSuccess:refresh});
  const error=create.error||start.error||stop.error;
  const ready=Boolean(name.trim()&&channel.trim()&&model.trim()&&Number(frequency)>0&&Number(count)>0&&Number(concurrency)>0&&deadline);
  return <><PageHeader title="探测任务" description="创建有频率、并发、次数、截止时间和停止条件约束的本地 Mock 探测；永不调用外部 Provider。"/>
    <div className="metric-grid four"><MetricCard label="运行模式" value="本地 Mock" meta="外部调用 0"/><MetricCard label="任务总数" value={tasks.data?.total??0}/><MetricCard label="安全频率" value={`≥ ${Math.ceil(60/Math.max(1,governance.data?.limits.channel.rate_per_minute??5))} 秒`}/><MetricCard label="渠道并发上限" value={governance.data?.limits.channel.concurrency??1}/></div>
    <Section title="创建探测任务" description="健康模板产生本地成功结果；故障模板用于验证失败停止，不生成计费流量。"><div className="form-grid clean"><label>任务名称<input value={name} onChange={event=>setName(event.target.value)} placeholder="例如 渠道健康冒烟探测"/></label><label>渠道 ID<input value={channel} onChange={event=>setChannel(event.target.value)} placeholder="真实渠道标识"/></label><label>模型 ID<input value={model} onChange={event=>setModel(event.target.value)} placeholder="模型目录中的 ID"/></label><label>请求模板<select value={template} onChange={event=>setTemplate(event.target.value as typeof template)}><option value="mock_success">本地健康响应</option><option value="mock_failure">本地故障注入</option></select></label><label>频率（秒）<input type="number" min="1" value={frequency} onChange={event=>setFrequency(event.target.value)} placeholder="不得低于安全频率"/></label><label>最大次数<input type="number" min="1" value={count} onChange={event=>setCount(event.target.value)} placeholder="请输入总次数"/></label><label>最大并发<input type="number" min="1" value={concurrency} onChange={event=>setConcurrency(event.target.value)} placeholder="请输入并发数"/></label><label>截止时间<input type="datetime-local" value={deadline} onChange={event=>setDeadline(event.target.value)}/></label><label>停止条件<select value={stopCondition} onChange={event=>setStopCondition(event.target.value as typeof stopCondition)}><option value="request_limit">达到次数上限</option><option value="first_failure">首次失败立即停止</option></select></label></div><div className="section-footer"><button disabled={!ready||create.isPending} onClick={()=>create.mutate()}>创建本地任务</button></div>{error&&<ErrorState title="探测任务操作被拒绝" description={message(error)}/>}</Section>
    <Section title="任务与最近结果" description="状态、最近结果和下次执行时间均来自 SQLite 持久化任务记录。">{tasks.error?<ErrorState title="探测任务读取失败" description={message(tasks.error)} onRetry={()=>tasks.refetch()}/>:tasks.data?.items.length?<div className="table-scroll"><table className="console-table"><thead><tr><th>状态</th><th>任务</th><th>渠道 / 模型</th><th>频率与进度</th><th>最近结果</th><th>下次执行</th><th>操作</th></tr></thead><tbody>{tasks.data.items.map(row=><tr key={row.task_id}><td><StatusBadge tone={tone(row.state)}>{row.state}</StatusBadge></td><td><b>{row.name}</b><small>{row.task_id}</small></td><td>{row.channel_id}<small>{row.model_id}</small></td><td>{row.frequency_seconds} 秒<small>{row.used_requests} / {row.max_requests} · 并发 {row.max_concurrency}</small></td><td>{row.last_result??"尚未执行"}<small>{formatLocalTime(row.last_run_at)}</small></td><td>{formatLocalTime(row.next_run_at)}</td><td>{["DRAFT","STOPPED"].includes(row.state)?<button className="text-button" onClick={()=>start.mutate(row.task_id)}>启动</button>:row.state==="RUNNING"?<button className="text-button" onClick={()=>stop.mutate(row.task_id)}>停止</button>:"已结束"}</td></tr>)}</tbody></table></div>:<EmptyState title="尚无探测任务" description="创建本地健康或故障任务后，可验证启动、停止和安全拒绝流程。"/>}</Section>
  </>;
}

export function LegacyTrafficGovernancePage(){
  const qc=useQueryClient();
  const query=useQuery({queryKey:["traffic-governance-page"],queryFn:({signal})=>api.trafficChangeStatus(signal)});
  const [environmentId,setEnvironmentId]=useState("china_uat");
  const [modelId,setModelId]=useState("");const [channelId,setChannelId]=useState("");
  const [rollout,setRollout]=useState("5");const [approval,setApproval]=useState("");
  const [sourcePolicy,setSourcePolicy]=useState("");const [targetPolicy,setTargetPolicy]=useState("");
  const [proposalReason,setProposalReason]=useState("");const [rollbackCondition,setRollbackCondition]=useState("");
  const propose=useMutation({mutationFn:()=>api.proposeTrafficChange({environment_id:environmentId,model_id:modelId,channel_id:channelId,change:{weight_percent:Number(rollout)},rollout_percent:Number(rollout),ttl_seconds:1800,idempotency_key:crypto.randomUUID()}),onSuccess:()=>qc.invalidateQueries({queryKey:["traffic-governance-page"]})});
  const approve=useMutation({mutationFn:(row:{proposal_id:string;revision:number})=>api.approveTrafficChange(row.proposal_id,{approval_reference:approval,expected_revision:row.revision,idempotency_key:crypto.randomUUID()}),onSuccess:()=>qc.invalidateQueries({queryKey:["traffic-governance-page"]})});
  const activate=useMutation({mutationFn:(row:{proposal_id:string;revision:number})=>api.activateTrafficChange(row.proposal_id,{expected_revision:row.revision,gate_results:Object.fromEntries((query.data?.required_gates??[]).map(name=>[name,true])),idempotency_key:crypto.randomUUID()}),onSuccess:()=>qc.invalidateQueries({queryKey:["traffic-governance-page"]})});
  const terminate=useMutation({mutationFn:(row:{proposal_id:string;revision:number})=>api.terminateTrafficChange(row.proposal_id,{expected_revision:row.revision,reason:"operator_stop",emergency:false}),onSuccess:()=>qc.invalidateQueries({queryKey:["traffic-governance-page"]})});
  const mutationError=propose.error||approve.error||activate.error||terminate.error;
  return <><PageHeader title="正式流量切换" description="当前仅运行离线沙箱控制面；真实生产适配器始终关闭，所有操作可审计且 network_called=false。"/>
    <Section title="安全边界"><div className="preview-summary"><StatusBadge tone={query.data?.real_execution_allowed?"danger":"success"}>{query.data?.real_execution_allowed?"真实执行已开启":"真实生产执行已关闭"}</StatusBadge><span>模式：{query.data?.mode??"读取中"}</span><span>最大灰度：{query.data?.maximum_rollout_percent??"未提供"}%</span></div></Section>
    <Section title="创建沙箱变更" description="成功场景会持久化 PROPOSED；超出灰度上限等失败场景由后端拒绝。"><div className="form-grid clean"><label>环境<input value={environmentId} onChange={event=>setEnvironmentId(event.target.value)}/></label><label>模型<input value={modelId} onChange={event=>setModelId(event.target.value)} placeholder="模型 ID"/></label><label>渠道<input value={channelId} onChange={event=>setChannelId(event.target.value)} placeholder="真实渠道 ID"/></label><label>灰度比例<input type="number" min="0.1" value={rollout} onChange={event=>setRollout(event.target.value)}/></label><label className="wide">审批引用<input value={approval} onChange={event=>setApproval(event.target.value)} placeholder="批准后用于职责分离的审批记录"/></label></div><button disabled={!environmentId||!modelId||!channelId||propose.isPending} onClick={()=>propose.mutate()}>创建沙箱变更</button>{mutationError&&<ErrorState title="治理操作被拒绝" description={message(mutationError)}/>}</Section>
    <Section title="Skill 流量提案" description="仅创建国内 UAT 提案，不授予 production_change，也不会激活生产流量。"><div className="form-grid clean"><label>来源策略版本<input value={sourcePolicy} onChange={event=>setSourcePolicy(event.target.value)} placeholder="选择真实已存在版本"/></label><label>目标策略版本<input value={targetPolicy} onChange={event=>setTargetPolicy(event.target.value)} placeholder="选择真实已存在版本"/></label><label>提案原因<input value={proposalReason} onChange={event=>setProposalReason(event.target.value)}/></label><label>回滚条件<input value={rollbackCondition} onChange={event=>setRollbackCondition(event.target.value)}/></label></div><BusinessSkillAction skillId="propose-traffic-switch" label="创建流量切换提案" argumentsValue={{source_policy_version:sourcePolicy,target_policy_version:targetPolicy,requested_percentage:Number(rollout),environment:"china_uat",reason:proposalReason,rollback_condition:rollbackCondition}} disabledReason={sourcePolicy&&targetPolicy&&proposalReason&&rollbackCondition?undefined:"请填写真实策略版本、原因和回滚条件"} confirmation/></Section>
    <Section title="变更记录">{query.error?<ErrorState title="流量治理状态读取失败" description={message(query.error)} onRetry={()=>query.refetch()}/>:query.data?.items.length?<div className="table-scroll"><table className="console-table"><thead><tr><th>状态</th><th>变更 ID</th><th>模型/渠道</th><th>灰度</th><th>到期</th><th>操作</th></tr></thead><tbody>{query.data.items.map(row=><tr key={row.proposal_id}><td><StatusBadge tone={tone(row.state)}>{row.state}</StatusBadge></td><td>{row.proposal_id}</td><td>{row.model_id}<br/><small>{row.channel_id}</small></td><td>{row.rollout_percent}%</td><td>{formatLocalTime(row.expires_at)}</td><td>{row.state==="PROPOSED"?<button className="text-button" disabled={!approval} onClick={()=>approve.mutate(row)}>批准</button>:row.state==="APPROVED"?<button className="text-button" onClick={()=>activate.mutate(row)}>验证门禁并激活</button>:row.state==="ACTIVE"?<button className="text-button" onClick={()=>terminate.mutate(row)}>停止</button>:"无可用操作"}</td></tr>)}</tbody></table></div>:<EmptyState title="尚无流量变更" description="创建一次本地沙箱变更即可验证持久化、审批和失败门禁。"/>}</Section>
  </>;
}

export {TrafficGovernanceControlPage as TrafficGovernancePage} from "./TrafficGovernanceControlPage";

export function AgentSkillPage(){
  const discovery=useQuery({queryKey:["formal-skill-discovery"],queryFn:({signal})=>api.formalAgentSkillDiscovery(signal)});
  const status=useQuery({queryKey:["formal-skill-status"],queryFn:({signal})=>api.formalAgentSkillStatus(signal)});
  const [skillId,setSkillId]=useState("");const [decisionId,setDecisionId]=useState("LOCAL-DECISION-1");const [argumentsText,setArgumentsText]=useState("{}");
  useEffect(()=>{if(!skillId&&discovery.data?.skills[0])setSkillId(discovery.data.skills[0].skill_id)},[skillId,discovery.data]);
  const invocation=useMutation({mutationFn:()=>{let args:Record<string,unknown>;try{args=JSON.parse(argumentsText)}catch{throw new Error("参数必须是合法 JSON 对象")}if(!args||Array.isArray(args)||typeof args!=="object")throw new Error("参数必须是 JSON 对象");return api.invokeFormalAgentSkill({skill_id:skillId,arguments:args,decision_id:decisionId,evidence_ids:[]})}});
  return <><PageHeader title="Agent Skill" description="正式 Skill 注册表、Schema 绑定与本地只读运行时；不签发浏览器 Grant，不执行网络或变更操作。"/>
    <div className="metric-grid four"><MetricCard label="注册 Skill" value={discovery.data?.skill_count??"读取中"}/><MetricCard label="注册表版本" value={discovery.data?.registry_version??"未提供"}/><MetricCard label="运行时" value={status.data?.status??"读取中"}/><MetricCard label="宿主接入" value="待外部配置"/></div>
    <Section title="本地只读测试调用" description="成功返回带审计 ID 的结构化结果；Prompt Injection、未知 Skill 或缺失参数会 fail-closed。"><div className="form-grid clean"><label>Skill<select value={skillId} onChange={event=>setSkillId(event.target.value)}>{discovery.data?.skills.map(item=><option key={item.skill_id} value={item.skill_id}>{item.skill_id} · {item.binding}</option>)}</select></label><label>Decision ID<input value={decisionId} onChange={event=>setDecisionId(event.target.value)}/></label><label className="wide">参数 JSON<textarea rows={5} value={argumentsText} onChange={event=>setArgumentsText(event.target.value)}/></label></div><button disabled={!skillId||!decisionId||invocation.isPending} onClick={()=>invocation.mutate()}>执行本地只读 Skill</button>{invocation.error&&<ErrorState title="Skill 调用被阻止" description={message(invocation.error)}/>} {invocation.data&&<div className="result-panel"><StatusBadge tone={tone(invocation.data.status)}>{invocation.data.status}</StatusBadge><p>Invocation ID：{invocation.data.invocation_id}</p><p>审计 ID：{invocation.data.audit_id}</p><p>不确定性：{invocation.data.uncertainty}</p><details><summary>脱敏结构化结果</summary><pre>{JSON.stringify(invocation.data.data,null,2)}</pre></details></div>}</Section>
    <Section title="已注册能力">{discovery.error?<ErrorState title="Skill 注册表读取失败" description={message(discovery.error)} onRetry={()=>discovery.refetch()}/>:discovery.data?.skills.length?<div className="table-scroll"><table className="console-table"><thead><tr><th>Skill</th><th>版本</th><th>绑定</th><th>权限边界</th></tr></thead><tbody>{discovery.data.skills.map(item=><tr key={item.skill_id}><td>{item.skill_id}</td><td>{item.version}</td><td>{item.binding}</td><td>只读 · 无网络 · 已审计</td></tr>)}</tbody></table></div>:<EmptyState title="尚无正式 Skill" description="注册表未返回任何 Skill。"/>}</Section>
  </>;
}
